# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7af67729f418dcb876ebfcd797e2b40647625a4ed7f8ad2b55e32564376ef5f3a9f34535846817dab4f5ebc03423467516ee1d18d21c07ce54ab359541551de

test:
  secret_key_base: 9a1e24c0825db33fb0748746441647abf176b8571b76246c11404ce7ea09ce6c5f39a246388bb8d244f7c14b5fb2af082d578da2b5cca104874be8da96b0fd23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
